### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by martialdessendier** [tzyganu/Switcher#100]
Hi,

I have a problem to install new version. Can you help me please ?

Here under the error message. 

Error in file: "/var/www/vhosts/dessendier.com/saveurs/app/code/community/Easylife/Switcher/sql/easylife_switcher_setup/install-2.0.0.php" - SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '9-General' for key 'UNQ_EAV_ATTRIBUTE_GROUP_ATTRIBUTE_SET_ID_ATTRIBUTE_GROUP_NAME', query was: INSERT INTO `eav_attribute_group` (`attribute_set_id`, `attribute_group_name`, `default_id`, `sort_order`) VALUES (?, ?, ?, ?)

Trace:
#0 /var/www/vhosts/dessendier.com/saveurs/app/code/core/Mage/Core/Model/Resource/Setup.php(645): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /var/www/vhosts/dessendier.com/saveurs/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '2.2.0')
#2 /var/www/vhosts/dessendier.com/saveurs/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('2.2.0')
#3 /var/www/vhosts/dessendier.com/saveurs/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /var/www/vhosts/dessendier.com/saveurs/app/code/core/Mage/Core/Model/App.php(417): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /var/www/vhosts/dessendier.com/saveurs/app/code/core/Mage/Core/Model/App.php(343): Mage_Core_Model_App->_initModules()
#6 /var/www/vhosts/dessendier.com/saveurs/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /var/www/vhosts/dessendier.com/saveurs/index.php(87): Mage::run('default', 'store')
#8 {main}

**Comment by tzyganu** [comment]
@martialdessendier Did you had a previous version of the module installed and you removed it?

**Comment by martialdessendier** [comment]
No, this is the very first installation. Before to proccess to a second installation, I went to your "uninstall section" to clean up everything. So I tryed a second installation but it hanged again.

**Comment by tzyganu** [comment]
I've never had this issue before,  but I will try to reproduce it.

**Comment by martialdessendier** [comment]
Thanks a lot in advance. It looks like tgere's a duplicate key when creating attribute

**Comment by tzyganu** [comment]
I will close this issue for now. I wasn't able to reproduce is. If you have some additional information post it here and I will reopen it.

**Comment by lorenaramonda** [comment]
Hi Marius, same problem here.
We use composer + vagrant. At first installation all ok, if we delete vendor folder then relaunch composer install this problem comes out. Also when i shut down the vagrant machine and start it up again. Probably missing a control "if already installed"?

Thank you!
