### ISSUE TITLE
Edit images

### ISSUE THREAD

**Issue by ViniciusAugusto** [tzyganu/Switcher#102]
In module 1.1.0 had the option to edit the images on file attribute, is to do this in version 2.0?

**Comment by tzyganu** [comment]
@ViniciusAugusto Please see [this documentation section](https://github.com/tzyganu/Switcher/wiki/configuration). in versions 2.0+ you can edit the settings for all attributes from the configuration section. For each attribute you can select one of the options:  None, Labels, Colors, Simple Product Images, Custom Images.  
For colors and custom images a button appears below the select. that button opens a popup where you can configure the colors and images for each attribute value.
