### ISSUE TITLE
Some issue

### ISSUE THREAD

**Issue by CjjmContinental** [tzyganu/Switcher#104]
1: Description and name not gets updated.
2: If Updating the description and name is not in the scope of this extension,how can i to do ?

Thank you.

**Comment by tzyganu** [comment]
@CjjmContinental I have no idea what you are trying to say. Please provide an example. A screenshot might help also.

**Comment by CjjmContinental** [comment]
I want to select the option to change the images,and change the description and name at the same time.

**Comment by tzyganu** [comment]
@CjjmContinental This is kind of broad and not in the scope of the extension. But if you want to give it a try you need to modify the config generated by the method `Easylife_Switcher_Block_Catalog_Product_View_Type_Configurable_Config::getJsonAdditionalConfig` to include an array with the product names and descriptions similar to [this line that contains the images](https://github.com/tzyganu/Switcher/blob/master/app/code/community/Easylife/Switcher/Block/Catalog/Product/View/Type/Configurable/Config.php#L259) then in the [js file](https://github.com/tzyganu/Switcher/blob/master/js/easylife_switcher/product.js) create functions that parse these values and replace the name and description, similar to how the image is changed by the function [changeImage](https://github.com/tzyganu/Switcher/blob/master/js/easylife_switcher/product.js#L316).  
That's all I can think of right now.

**Comment by CjjmContinental** [comment]
Thank you very much.
