### ISSUE TITLE
Related Products Issue

### ISSUE THREAD

**Issue by dclinton** [tzyganu/Switcher#105]
It seems Easylife Switcher is causing the first image in the "Related Products/You May Also Like" Section to be replaced with the main image - do you have any insight on this?
Thanks

**Comment by tzyganu** [comment]
@dclinton  I didn't experience this before. Can you post the link where I can see this? 
Most probably there is a problem with the dom selector for your main image. It may select multiple images in the page.

**Comment by dclinton** [comment]
Thanks for the quick response im away from a computer but will get back to asap


Sent from my Verizon Wireless 4G LTE smartphone

<div>-------- Original message --------</div><div>From: Marius Strajeru <notifications@github.com> </div><div>Date:04/17/2015  9:42 AM  (GMT-05:00) </div><div>To: tzyganu/Switcher <Switcher@noreply.github.com> </div><div>Cc: dclinton <dclinton_22@hotmail.com> </div><div>Subject: Re: [Switcher] Related Products Issue (#105) </div><div>
</div>
@dclinton  I didn't experience this before. Can you post the link where I can see this?
Most probably there is a problem with the dom selector for your main image. It may select multiple images in the page.

---

**Comment by dclinton** [comment]
Here is an example
 
http://www.miansai.com/shop/mens/mens-bracelets/beacon-leather-4dba70
 
then click the first related product below.
 
Date: Fri, 17 Apr 2015 10:10:13 -0400
Subject: RE: [Switcher] Related Products Issue (#105)
From: dclinton_22@hotmail.com
To: reply@reply.github.com; Switcher@noreply.github.com






Thanks for the quick response im away from a computer but will get back to asap







Sent from my Verizon Wireless 4G LTE smartphone





-------- Original message --------
From: Marius Strajeru 
Date:04/17/2015 9:42 AM (GMT-05:00) 
To: tzyganu/Switcher 
Cc: dclinton 
Subject: Re: [Switcher] Related Products Issue (#105) 




@dclinton I didn't experience this before. Can you post the link where I can see this?


Most probably there is a problem with the dom selector for your main image. It may select multiple images in the page.

—

Reply to this email directly or 
view it on GitHub.

**Comment by dclinton** [comment]
This is all set now - was a config issue.  thanks.
 
From: dclinton_22@hotmail.com
To: reply@reply.github.com; switcher@noreply.github.com
Subject: RE: [Switcher] Related Products Issue (#105)
Date: Fri, 17 Apr 2015 11:17:50 -0400




Here is an example
 
http://www.miansai.com/shop/mens/mens-bracelets/beacon-leather-4dba70
 
then click the first related product below.
 
Date: Fri, 17 Apr 2015 10:10:13 -0400
Subject: RE: [Switcher] Related Products Issue (#105)
From: dclinton_22@hotmail.com
To: reply@reply.github.com; Switcher@noreply.github.com






Thanks for the quick response im away from a computer but will get back to asap







Sent from my Verizon Wireless 4G LTE smartphone





-------- Original message --------
From: Marius Strajeru 
Date:04/17/2015 9:42 AM (GMT-05:00) 
To: tzyganu/Switcher 
Cc: dclinton 
Subject: Re: [Switcher] Related Products Issue (#105) 




@dclinton I didn't experience this before. Can you post the link where I can see this?


Most probably there is a problem with the dom selector for your main image. It may select multiple images in the page.

—

Reply to this email directly or 
view it on GitHub.

**Comment by tzyganu** [comment]
@dclinton I'm glad it was fixed. I will close this issue now, but please explain in a few words what was the problem in case other people run into it. Thanks in advance.
