### ISSUE TITLE
Can't load simple product images

### ISSUE THREAD

**Issue by MoniqueStolp** [tzyganu/Switcher#106]
Hey,

I've installed your extension, but I have a few problems.
1. When I select Simple Product Images for the attribute transformer, the images don't show on the frontend. Only labels.
2. The main image won't change when I select a color.

I have the idea these two issues are somehow related.

Could you please help me?

I'm using CE 1.9.1 with a custom theme.

Greetings,
Monique

**Comment by tzyganu** [comment]
@MoniqueStolp Make sure that the simple products have images assigned to them and that you are using the right image. I mean make sure the simple products have a base image or small image or thumbnail. Also a link to your website might help me identify the problem.

**Comment by MoniqueStolp** [comment]
@tzyganu Thank you for your quick answer,

All simple product have images assigned to them. They all have a base, small and thumbnail image.
This is my website:
http://wollendekensonline.nl.testbyte.nl/index.php/nld/wollen-dekens/corona-wollen-deken.html

And these are the settings I used.
![screenshot](https://cloud.githubusercontent.com/assets/6596652/7247209/50c2d438-e807-11e4-929b-6f00ac4fb519.png)

**Comment by CjjmContinental** [comment]
@MoniqueStolp  I'm using CE1.8
I select Switch product images option :switch main Image, the main image won't change when I select a color.But  'select Switch all media section', it's work

**Comment by MoniqueStolp** [comment]
@CjjmContinental Thank you! This fixed it for me. And when I change "thumbnail" to "base image" the "simple product images" also works!

**Comment by MoniqueStolp** [comment]
Only product zoom stopped working. I used the following code for the JS Callback:
ProductMediaManager.destroyZoom();
ProductMediaManager.createZoom(jQuery('#image-main'));ProductMediaManager.init();

In my console I get this error:
Uncaught ReferenceError: ProductMediaManager is not defined

**Comment by tzyganu** [comment]
In order to make it work when you have the "switch main image" on you need to set the value for `Main image selector` to `$$('zoom1 img')[0]`. And in order to make the zoomer work, just fill in the config section 'Js Callback after main image change' to the code needed to reinitialize your zoomer.  Do you ever reed any documentation before posting issues?
