### ISSUE TITLE
Transformation settings not shown in backend

### ISSUE THREAD

**Issue by papillon6** [tzyganu/Switcher#107]
Hi!
After installing current version (master) via modman, no "Transformation settings" are shown at all in magento-backend (1.7). The label "Transformation settings" is displayed without any form or inputs...

Is this a known issue? Any suggestions on this?

**Comment by tzyganu** [comment]
Is the `allow symlinks` setting set to Yes? https://github.com/colinmollenhour/modman#requirements

**Comment by papillon6** [comment]
It wasn't... 

:thumbsup:
Thanks tzganu!
