### ISSUE TITLE
Image change saving

### ISSUE THREAD

**Issue by Anvo54** [tzyganu/Switcher#111]
Is there some limit on setting "Change images when these attributes are changed"?

It seems i can't save more than 59 Attributes to change image. If I unselect some attribute I can save new one. but no more than 59.

**Comment by tzyganu** [comment]
@Anvo54 I think the limitation comes from the database.  
For the attributes that you select, their codes are concatenated using comma as a separator and they are saved in the `core_config_data` table. I think you reach the max column length.

There is also a chance that you send a lot of data through post and you go over the max limit for the POST.  


You can test these theories easily.  
for the first one look in the table `core_config_data` for the record with path = `easylife_switcher/settings/change_image_attributes`, edit the `value` column and add a few more characters at the end. If they are not saved that's the issue.  

The second one you can test by increasing the `post_max_size` php var.  

Let me know if I'm right.

**Comment by Anvo54** [comment]
I tought that it was a database problem. I tried to write in core_config_data. And it saved with no problems at all. Then I tried to look up php.ini and found that there is no post_max_size. Should I add in a line?

**Comment by tzyganu** [comment]
Yes, you can try to add the line.

**Comment by Anvo54** [comment]
I added the line post_max_size = 32M but still it keeps at the same. If I Select new value to change image it saves it but automatically it deselect values that I saved last time. So if I select one new value it takes one value off.

**Comment by tzyganu** [comment]
@Anvo54 I'm out of ideas. I don't have a magento instance with 60+ configurable attributes but when I have some time I will create one and test your issue.

**Comment by tzyganu** [comment]
@Anvo54 I tested with 100+ configurable attributes and everything worked smoothly. I was able to add all of the attributes to change the image when changed.  
I can conclude this is not an issue with the extension itself.  
I will closed the issue for now as I cannot reproduce it. If you find additional information on how to reproduce it feel free to add it here and I will reopen it.
