### ISSUE TITLE
Position of attributes values in the product page

### ISSUE THREAD

**Issue by LudovicLapert** [tzyganu/Switcher#118]
Hello,

I am using the module Easylife Switcher on my website : http://occasion.m-budget.migros.ch

I noticed that the position of each attributes values is changing for each product page.
For example:
iPhone 5: http://occasion.m-budget.migros.ch/apple-iphone-5.html
For the attribute "Capacity" you can see : 1) 16GB 2) 64GB 3)32GB

iPhone 4S: http://occasion.m-budget.migros.ch/apple-iphone-4s.html
For the attribute "Capacity" you can see : 1) 64GB 2) 32GB 3) 8GB 4) 16GB

I would like to have the same order (ascending order) for each product page 1) 8GB 2) 16GB 3) 32GB ...
As you can see in the screenshot attached it seems to be well configured in the admin, doesn't it ?
![capacity](https://cloud.githubusercontent.com/assets/12862358/8133499/fc525db0-1128-11e5-9f52-2cc299de0c87.JPG)

Thank you for your help.

Ludo

**Comment by tzyganu** [comment]
@LudovicLapert  If you disable the functionality of the extension from system->configuration->Easylife switcher->settings->Enabled, do you see the options in a different order?  
This extension should not affect the order of the options.

**Comment by LudovicLapert** [comment]
Hello @tzyganu,
Thank you for you answer.
You are right the extension does not affect the order: I disabled it and I still have the wrong order...

Do you know how I can solve this problem ?

**Comment by tzyganu** [comment]
@LudovicLapert  Sorry, I have no idea how magento does it or how you can change it. I will close this issue since is not cause by the extension itself.
