### ISSUE TITLE
Installation Error: Class 'Easylife_Switcher_Model_Resource_Setup' not found

### ISSUE THREAD

**Issue by applepiepro** [tzyganu/Switcher#121]
Got this error after installing the extension on my staging server and trying to login again: 

Fatal error: Class 'Easylife_Switcher_Model_Resource_Setup' not found in /home/in2print/public_html/staging/includes/src/Mage_Core_Model_Resource_Setup.php on line 234

Please help

**Comment by tzyganu** [comment]
@applepiepro Never install extensions with compiler enabled.  
Disable the compiler, install the extension and enable it again.
