### ISSUE TITLE
Images not switching

### ISSUE THREAD

**Issue by sumit-drish** [tzyganu/Switcher#124]
Hi,
I installed your extension in magento 1.9.1.1. Everything is working fine except, Images are not switching when I select a different color. I need to switch whole media section but nothing is happening.
I have 2 attributes size and color and I have added images for one of the simple products having size "S" and color "Blue" and also for "S" size of "Black" color but not for other sizes. And in configuration I have selected to change images on color change.
Please help me out.
Thanks in advance..!!

**Comment by tzyganu** [comment]
@sumit-drish Sorry for the late response.  Check if your settings are OK. Go to system->onfiguration->Easylife Switcher and see the value for `Dom selector for main image`. This should be the js selector for getting the main image. Maybe your theme is different and it does not use the same selector as the default theme.

**Comment by mv8ang** [comment]
I had the same issue, what I did was added
>jQuery('*').removeClass('visible');
>jQuery('#image-main').addClass('visible');

to the JS callback.

**Comment by tzyganu** [comment]
This is not look like an extension problem. It looks like  a configuration problem.
