### ISSUE TITLE
Select thumb bug

### ISSUE THREAD

**Issue by weblance2** [tzyganu/Switcher#125]
I have used this successfully on another site and it is a great extension. I am experience some issues with the extension now that happens both on default magento and with the Argento Flat theme. 

On page:http://staging.buddyrest.com/comfort-deluxe-memory-foam-bed.html

1. When selecting a color (thumb of simple product image) the main image in the viewer does shows blank.
2. When selecting a thumb like this one http://grab.by/IAgG there is a strange pop up which is often 404.

I have the magento swatches disabled.

Hey any help with this one would be really appreciated. Site access would be available. I can PM you with an email perhaps...

Thanks again! I do love this extension, seems like an obvious need for core!

**Comment by tzyganu** [comment]
@weblance2 I checked your link and there is no trace of my extension. I think you are using something else.
