### ISSUE TITLE
Configuration Options Not Visible

### ISSUE THREAD

**Issue by zachmb** [tzyganu/Switcher#126]
I've installed your extension and everything works great! Even in my highly customized theme. I was very impressed, and this solves A LOT of problems for me. So first off, thank you very much for this.

I am having a strange issue with configuring the Transformation Settings for your module, however. Your Wiki shows options to configure the variation attribute dropdown menus into (instead) text labels, for example. But I just straight up do not see any of those options under:
`System > Configuration > Catalog > Easylife Switcher`
...it's very odd! (See my attached screenshot for further details.) Is there somewhere else in the backend that I should be looking for this?

I have a deep suspicion it's user error on my part, and that there's a very quick setting to enable or place to go to see the configuration options that will let me style each of my variation attributes on the frontend.

Thanks in advance!

![easylifeswitcher_ss](https://cloud.githubusercontent.com/assets/6172425/8528792/17b5a05c-23db-11e5-8676-7bf4d701880f.png)

**Comment by tzyganu** [comment]
@zachmb Make sure you have attributes that can be used for creating configurable products. In the section transformation aettings you should see all the attributes that can be used

**Comment by zachmb** [comment]
I definitely have attributes that are marked as "for use in creating Configurable products"...most of our products are configurable products. What's weird is the "Transformation settings" just shows a blank space where the fields could be (it's visible in my screenshot). Not sure if it's a bug with Magento 1.9.1.1, or what? Hm!

Regardless, I wrote my own label code that hides the dropdown and uses a Prototype `simulate('change')` method to invoke all the same functions as using the dropdowns.

Thanks a bunch for this! You saved me countless hours of development!

**Comment by tzyganu** [comment]
@zachmb I will check on the 1.9.1.1 version and come back with an answer. I think the latest one I checked is 1.9.1.0.

**Comment by In2ideas** [comment]
Had the same situation. Everything worked just fine until after installing (and uninstalling) the extension "Simple Configurable Products (OrganicInternet)". The extension had broken this extension (all of a sudden the dropdown-list showed up) but also the display of the atributes in te dropdowns
Also after re-indexing, clearing the cache, no difference.
After re-entering the backend a few hours later, the "Configuration Options" were back again.  Weird.

**Comment by to8gal** [comment]
do you have a guess how they came back? I´m in the same situation with no results

**Comment by to8gal** [comment]
Thanks, I tried that, to me was the .gitignore impeding the admunhtml files to be updated on the live site, fixed it, thanks absolutely for the fine fast answer
