### ISSUE TITLE
empty attribute

### ISSUE THREAD

**Issue by metalzone82** [tzyganu/Switcher#127]
When enable the modules in front office see empty attributes?why?
thanks
![untitled-2](https://cloud.githubusercontent.com/assets/8060988/8543797/0ad2e4ce-24a0-11e5-872d-27176ea6f7ab.jpg)

**Comment by tzyganu** [comment]
@metalzone82  Can you post a link to your website? Also please specify the magento version. I'm not able to reproduce this.

**Comment by tzyganu** [comment]
I'm closing this issue as it cannot be reproduced and there is not feedback from the OP in more than 10 days.
