### ISSUE TITLE
Tzyganu Deserves a medal.

### ISSUE THREAD

**Issue by eddtuk** [tzyganu/Switcher#129]
URGENT.

Please. accept my heartfelt thanks.  This is an issue.  Take a few minutes, and pat yourself on the back for writing something that really, REALLY helped me.

Thank you SO MUCH.

Seriously.

Thanks.

and again,

Thanks.

**Comment by tzyganu** [comment]
@eddtuk The issue has been solved and will be deployed on the next version. 
I will close the issue for now.

(Thanks for the nice words),
