### ISSUE TITLE
Stock availability (configurable products)

### ISSUE THREAD

**Issue by miguel-martin** [tzyganu/Switcher#136]
Hi there, Marius.

Thank you so much for this wonderful extension.

I noticed something and I think it must be a bug. Steps to reproduce (Magento 1.9):
1) Install and activate EasyLife Switcher. Configure it to allow showing items out of stock.
2) Create configurable product (Stock tab > Manage Inventory = Yes, make product available).
3) Create a simple product associated to configurable product with stock=0. Make it not visible individually.
4) Navigate to product page. It says Availability: Available. And since the configurable has only a simple product with no stock, it should NOT be available.
5) Deactivate EasyLife Switcher. The status of the configurable becomes then "Not available" (which is the right thing to happen).

I noticed this trying to set up alerts to stock products. The isAvailable function is returning true when it should return false. 

I would REALLY appreciate if you could tell me how to fix this.

Thanks in advance!

(I thought this was a Magento bug: http://magento.stackexchange.com/questions/79317/function-isavailable-always-returning-true-for-configurable-products)

**Comment by tzyganu** [comment]
@miguel-martin see #122. Let me know if it the same as what you are experiencing.

**Comment by miguel-martin** [comment]
Well, yes it seems to be. Sorry for not having read that before asking.

The patch supplied in #122 does work? From a first glance, it "fixes" the <em>'Availabilty: Available'</em> text issue in the product page, but... woud it fix also the 'incorrect' value returned by <code>isAvailable()</code> function? If so, could this be integrated into a new version of your extension?

I would really be able to fix this myself and provide the patch, but I am a total newbie to Magento and this falls way out of my knowledge area. I am willing to help in any way I can, though.

What I will try is to edit app/code/core/Mage/ProductAlert/Block/Product/View.php and remove the <code>isAvailable()</code> check, so that the "Suscribe to stock alerts" link is always visible, no matter what the stock is for configurable product. But this is kind of a nasty thing to do. And I don't know if the alerts to the configurable products will ever work, because to Magento, the configurable product will always be in stock :-/

**Comment by tzyganu** [comment]
@miguel-martin I haven't tested the patch. but this seams to be a limitation of Magento, not an issue from the extension. I work with what I have and try to rewrite as less as possible (preferably nothing).
