### ISSUE TITLE
Change default option for dropdown

### ISSUE THREAD

**Issue by mv8ang** [tzyganu/Switcher#139]
Bit weird but here goes.

Right now on the configurable product page, there's a label above the dropdown with the name of the attribute, for example "Color", then the default option of the dropdown is "Please select...". Is there a way to remove the label and change the option to "Please select <attribute name>"?

**Comment by tzyganu** [comment]
I don't really understand what the problem is. Can you add a screenshot?

**Comment by mv8ang** [comment]
![This is what the default dropdown for configurable products looks like](http://i.imgur.com/YdIv2Tr.png).

This is what the default dropdown for configurable products looks like. Color (Farve) is the label, and Please Choose... (Vælg Venligst...) is the default option.

![This is what I'm trying to do](http://imgur.com/5UsdMzQ.png). 

This is what I'm trying to do. Is it possible? 

I'm sorry it's not a problem per se, I'm just wondering if the extension allows it.

Thanks in advance and sorry for the weird language :)

**Comment by tzyganu** [comment]
@mv8ang I see what you mean. Sorry, but the extension does not support this. And is not planned in the near future either.
