### ISSUE TITLE
not working in safari browser

### ISSUE THREAD

**Issue by purvi123** [tzyganu/Switcher#141]
hello,
when change option in safari get error "EvalError: The "this" value passed to eval must be the global object from which eval originated"

**Comment by tzyganu** [comment]
@purvi123 thanks for reporting this. I will investigate soon. but can you please post the magento version you are using?

**Comment by purvi123** [comment]
I am working in amgento 1.9.1.1

**Comment by purvi123** [comment]
have u find any solution?

**Comment by tzyganu** [comment]
sorry I didn't have time to check.

**Comment by purvi123** [comment]
Hello,this issue is solved.
