### ISSUE TITLE
Not able to install on Magento ver. 1.9.1.0

### ISSUE THREAD

**Issue by talenyc** [tzyganu/Switcher#142]
I am having issues installing this on Magento ver. 1.9.1.0. I was on latest version and then I downgraded to Magento ver. 1.9.1.0 to use this plug in. 

I installed using modman
- CD /Applications/MAMP/htdocs 
- modman init 
 - clone https://github.com/tzyganu/Switcher/
I enabled Allow Symlinks
Verified Compile is disabled 
 
Verified that  attribute default_configuration_id doesn't exist
Set Configurable Swatches Enabled = No
Clear Cash 
Log-out and log back in. 

I still don't see option under System>Configuration> CATALOG

**Comment by tzyganu** [comment]
does you module appear in `System->configuration->Advanced` in the list of installed modules?

**Comment by talenyc** [comment]
I don't see it. I am running on Mac OSX 10.10.5

Here is a list of modules listed.

Cm_RedisSession
Mage_Admin
Mage_AdminNotification
Mage_Api
Mage_Api2
Mage_Authorizenet
Mage_Backup
Mage_Bundle
Mage_Captcha
Mage_Catalog
Mage_CatalogIndex
Mage_CatalogInventory
Mage_CatalogRule
Mage_CatalogSearch
Mage_Centinel
Mage_Checkout
Mage_Cms
Mage_Compiler
Mage_ConfigurableSwatches
Mage_Connect
Mage_Contacts
Mage_Core
Mage_Cron
Mage_CurrencySymbol
Mage_Customer
Mage_Dataflow
Mage_Directory
Mage_Downloadable
Mage_Eav
Mage_GiftMessage
Mage_GoogleAnalytics
Mage_GoogleCheckout
Mage_ImportExport
Mage_Index
Mage_Install
Mage_Log
Mage_Media
Mage_Newsletter
Mage_Oauth
Mage_Page
Mage_PageCache
Mage_Paygate
Mage_Payment
Mage_Paypal
Mage_PaypalUk
Mage_Persistent
Mage_Poll
Mage_ProductAlert
Mage_Rating
Mage_Reports
Mage_Review
Mage_Rss
Mage_Rule
Mage_Sales
Mage_SalesRule
Mage_Sendfriend
Mage_Shipping
Mage_Sitemap
Mage_Tag
Mage_Tax
Mage_Usa
Mage_Weee
Mage_Widget
Mage_Wishlist
Mage_XmlConnect
Phoenix_Moneybookers

**Comment by tzyganu** [comment]
It looks like the declaration file is not picked up by magento. Make sure it's readable. I'm not able to reproduce this issue.
