### ISSUE TITLE
image swap not working

### ISSUE THREAD

**Issue by farhanzafar** [tzyganu/Switcher#144]
My site have too many colors value, I got the error when i change base images. i get # on url 
 
here product link http://goo.gl/4FLKzL additional image cant change kindly help me on this issue

**Comment by tzyganu** [comment]
This is a duplicate of #124. Please read the [configuration section of the wiki](https://github.com/tzyganu/Switcher/wiki/configuration). The problem is not with the extension itself. You have to configure it properly to work with your theme.
