### ISSUE TITLE
Can't find in the admin section..

### ISSUE THREAD

**Issue by 007kishore** [tzyganu/Switcher#146]
I extracted  the package from zip and put the files in its respective places in the magento instance. But  there is no section called "Easylife Switcher".  
There is also no record in the tables "core_config_data" and "core_resource" related to the extension.
Kindly suggest me how to do it in a proper way.
 Thanks.

**Comment by tzyganu** [comment]
@007kishore This means the extension was not installed. Try clearing the cache. Also check if you have the file `app/etc/modules/Easylife_Switcher.xml`.

**Comment by 007kishore** [comment]
Yes it is present and it is active. I can also see it from admin site  in system->configuration->Advanced->Advanced. It is enabled there. I have cleared the cache also.  But still I can't find why it is not showing.

**Comment by 007kishore** [comment]
@tzyganu  I have followed all the process defined here (http://magento.stackexchange.com/questions/6476/magento-custom-module-is-showing-in-advanced-tab-but-not-showing-in-admin-config) but still not succeded..Can you please suggest what should I do ?

**Comment by tzyganu** [comment]
@007kishore Sorry, but I cannot reproduce your problem. I tried to install the extension and everything works smoothly. The only thing I can think about now is that you may not have read permissions on the extension files.

**Comment by 007kishore** [comment]
@tzyganu Thank you. It was the exact problem..The read Permission.
