### ISSUE TITLE
Image not switching?

### ISSUE THREAD

**Issue by rmvdev** [tzyganu/Switcher#150]
Hey Tzyganu, first of all - thank you for the free extension!

I understand this is unlikely to be a bug with the extension itself but I'm really struggling!

We use Porto (the most popular magento theme) which I believe uses Fancy Images for media, but no matter what solution I find I cannot get images to switch when an option is selected

Each simple product has an image defined and I've looked into the source of our product view but cant find the main images "IMG ID" .

Any ideas?

My source looks like this - 

<ul id="etalage_NGYwOTVhMjI3YWY3YTRjZDA0NDZhZmFkNDkyYjFjNDE" class="etalage" style="display: block; width: 337px; height: 337px;">

**Comment by tzyganu** [comment]
@rmvdev I'm not familiar with the Porto theme. Most likely the image and media block does not use the same markup as the default theme.  
Read the [configuration manual](https://github.com/tzyganu/Switcher/wiki/configuration) to see what each field does and see how you can configure the extension.
