### ISSUE TITLE
only 3 images are accepted in associated products

### ISSUE THREAD

**Issue by lalitvohra** [tzyganu/Switcher#155]
I have installed your extension on 1.9.1.0. Everything is working fine except that when I add more than 3 product images to associated product (while creating a configurable product) while switching only the base image changes and rest of the images are not visible, I have already configured the extension for changing entire media block and not just main image.

Please help
Great extension 

Thanks in advance

**Comment by tzyganu** [comment]
@lalitvohra I tried to reproduce this, but I cannot. Check if your custom theme is not the problem. See if it works on the default theme.
