### ISSUE TITLE
Much Better Than Built In Magento Functionality. Just One Error

### ISSUE THREAD

**Issue by johnnywokka** [tzyganu/Switcher#156]
I am using this fantastic swatch extension - It's dramatically better than the built in magento function.

The only problem is that I'm using the porto theme that has a sticky add to cart option and I'm getting the error below in the console:-
**Uncaught TypeError: Product.ConfigurableSwatches is not a constructor**

How would I fix this? If it's possible.

Thanks again for coding this extension!

**Comment by tzyganu** [comment]
Try disabling the code color swatches functionality.  
If that does not work...well...

> My extension does not conflict with your theme. 
> Your theme conflicts with my extension.

**Comment by johnnywokka** [comment]
@tzyganu 

Sorry - I meant to report back and forgot.

It was a theme conflict. Once I removed the themes support for built in magento swatches the conflict vanished.

Thanks again for this extension. It's loads better than built in magento one :+1:

**Comment by apothegm** [comment]
@johnnywokka 

I also am getting this error using the RWD theme. I have magento's built-in swatches functionality disabled but I still see the error.

How were you able to resolve this?
