### ISSUE TITLE
Not Working with Ajax Catalog Product View

### ISSUE THREAD

**Issue by vikas529** [tzyganu/Switcher#159]
I am loading Catalog Product View in Ajax in which it is not working.

$product = Mage::getModel('catalog/product')->load($product_id); 

$product = Mage::helper('catalog/product')
			->initProduct($product->getId(), $this);

$this->getLayout()->getUpdate()->addHandle(array(
	    'default',
	    'catalog_product_custom_view',
	    'PRODUCT_TYPE_' . $product->getTypeId(),
	    'PRODUCT_' . $product->getId()
	));

Mage::dispatchEvent('catalog_controller_product_view', array('product' => $product));
Mage::getSingleton('catalog/session')->setLastViewedProductId($product->getId());
$this->loadLayout();
$this->getLayout()->removeOutputBlock('root')->addOutputBlock('content');
$this->renderLayout();

Where all data is loading other than working of this module

**Comment by tzyganu** [comment]
@vikas529 Actually "Ajax Catalog Product View" is not working with this extension.  
I cannot make this compatible with every extension that exists out there.
