### ISSUE TITLE
Image not display on front end.

### ISSUE THREAD

**Issue by bhargav31** [tzyganu/Switcher#161]
Hi,
i have upload images from admin but it is not display on front end can you please tell me.

Here i attached screen sort too. We have a lots of color is this a problem?

Regards,
Bhargav
![adminpanel_white](https://cloud.githubusercontent.com/assets/20220244/16479495/48cd0398-3ebe-11e6-9089-a528531f0d79.png)
![frontend](https://cloud.githubusercontent.com/assets/20220244/16479496/48cd5816-3ebe-11e6-9c7c-948da2e1d6aa.png)

**Comment by tzyganu** [comment]
If you inspect the image element with firebug or developer tools what does it say? What's the content of the html markup? or the image src?

**Comment by bhargav31** [comment]
Thanks i have set method post and it is working right now. my client is adding images for colors now. More then 200+ colors we have hope it will work fine with out any issues.

**Comment by tzyganu** [comment]
@bhargav31 So can I close this now?

**Comment by bhargav31** [comment]
yes.

**Comment by bhargav31** [comment]
Thank you for your support.
