### ISSUE TITLE
Out of stock options

### ISSUE THREAD

**Issue by fritzelly** [tzyganu/Switcher#162]
The plugin is installed and working OK but the out of stock options in a configurable product are not disabled and hence can be selected to add to cart

This is on 1.9.2

I assume these are correctly set:

Show out of stock configurations		Yes
Allow out of stock products to be selected	No

Any ideas?

**Comment by tzyganu** [comment]
@fritzelly it should work like that.  But if you installed this on 1.9, you should disable the core swatches module. It does not play well when that one is active.

**Comment by tzyganu** [comment]
Closed due to inactivity
