### ISSUE TITLE
There is no document to show how to configure at list page

### ISSUE THREAD

**Issue by murtuza5253** [tzyganu/Switcher#167]
There is no document or no code for apply this extension at list page

**Comment by tzyganu** [comment]
No, there isn't. It's not in the scope of this extension.

**Comment by murtuza5253** [comment]
is there any way to integrate this to list page??

**Comment by tzyganu** [comment]
@murtuza5253 Read my previous response. No there is no way to integrate this in the list page. It's not in the scope of this extension.
