### ISSUE TITLE
How to show the default simple product price on product list

### ISSUE THREAD

**Issue by matiasmm** [tzyganu/Switcher#171]
I've been using this extension and it works well on the Product Page.
But on the rest of the pages, like in the frontend product catalog it does not display the default image nor the default price. Instead it shows the price from configurable product. Is there a way I can get to it to show the price from the simple product selected by default?

**Comment by tzyganu** [comment]
@matiasmm The purpose of this extension is to change the behavior on the product view page. It does not affect the parduct list page.
