### ISSUE TITLE
Menu dropdown isn't working in the product pages

### ISSUE THREAD

**Issue by d3viliz3d** [tzyganu/Switcher#174]
Hello,

The extension still work pretty good even though it's old, I'm using it on a Magento 1.9.2.4 installation. The only issue so far is that the menu dropdowns doesn't work in the Products page, probably some Js conflict.

Any idea on how to solve this?

**Comment by tzyganu** [comment]
@d3viliz3d I have no idea how to solve it. I don't even know what the problem is. If it works on the default theme with no extensions installed then it may conflict with something in your theme or 3rd party module.  
Anyway, this extension is discontinued due to mostly lack of time.

**Comment by d3viliz3d** [comment]
Ok thank you anyway!
