### ISSUE TITLE
Issue regarding product detials are not showing on frontend

### ISSUE THREAD

**Issue by shubh1105** [tzyganu/Switcher#178]
Hello,

I have installed this extension and it is working properly but i am facing problem that in product list page the product which is selected by default in configurable product so it is not showing in product list page.but it is showing default product for that configurable product so is there any solution so that product default values will also show in frontend product list page.??

**Comment by tzyganu** [comment]
@shubh1105 I'm sorry, but this extension is discontinued due to lack of time to take care of it.
