### ISSUE TITLE
JS brakes when Combine JS is enabled.

### ISSUE THREAD

**Issue by epiblue** [tzyganu/Switcher#70]
Hey,

The js script brakes on my review page when it is combined. When I disable the JS combine feature in Magento backend everything works, but I would like to keep it combined, for optimization.

Here is the preview of the code that is first to cause problems - event-simulate.js:
![error](https://cloud.githubusercontent.com/assets/6641569/5159372/a0baefba-7364-11e4-90b3-89a870fcf248.jpg)

**Comment by tzyganu** [comment]
I tried multiple times to reproduce this issue but failed. For me it worked nicely with jquery and other plugins. Most probably you have one script wrongly formatted or that is missing a semicolon
