### ISSUE TITLE
Getting Default Value

### ISSUE THREAD

**Issue by dmanners** [tzyganu/Switcher#72]
Not completely sure if this would help but could you simply load the raw values using `getAttributeRawValue` rather than loading to complete default product in https://github.com/tzyganu/Switcher/blob/master/app/code/community/Easylife/Switcher/Block/Catalog/Product/View/Type/Configurable/Config.php

Obviously happy to investigate this myself and do a pull request when I have some time :)

**Comment by ajinets1012** [comment]
Hi,

This not working with my custom theme and package. I had installed the same and founds no changes in front end and not working in front end.

**Comment by tzyganu** [comment]
@ajinets1012 https://twitter.com/MariusStrajeru/status/540049314069102592

**Comment by ajinets1012** [comment]
@tzyganu I checked for conflicts with my theme. But there is no conflicts found. I checked it with envato sm market theme and found its not working with that theme too. I am using magento 1.9.1 CE. Please help me to resolve this issue .

**Comment by tzyganu** [comment]
@ajinets1012 Check on the default rwd theme. If it works there, it means that there is a problem with your theme. Also make sure the feature is enabled from system->configuration. Clear the cache just in case. I have no other idea. I cannot fix what I cannot reproduce.

**Comment by ajinets1012** [comment]
@tzyganu thanks for updating. I will check and reply back you soon.

**Comment by ajinets1012** [comment]
@tzyganu Sorry, but its not working with rwd theme too.

**Comment by tzyganu** [comment]
Make sure the extension is enabled (System->configuration->Easylife Switcher).

**Comment by ajinets1012** [comment]
@tzyganu , Plugin is enabled. Cache flushed and cache is disabled. But there is no change. Will check with a fresh magento installation and will reply back you soon. I appreciate you for the support you are giving. Thanks bro.

**Comment by oviliz** [comment]
Could be some other extension conflicting.
