### ISSUE TITLE
Re sizing label/option size result in white boarder instead?

### ISSUE THREAD

**Issue by Jerry-Yocupco** [tzyganu/Switcher#87]
Seem like by making the label/options size smaller than the defaulted 40 would create white boarder instead of actually shrinking the label size?  the actual label seem to be offset to the top left.
![capture2](https://cloud.githubusercontent.com/assets/8918594/5589905/dd6f9154-90dd-11e4-8a03-e6cc5da76fd1.PNG)

Also, it is possible to include the option text after the option title, for say, Color*, into Color*: Red  
The 1.9.1 native swatch have this function already so I think it maybe an easy add on?

**Comment by tzyganu** [comment]
@Jerry-Yocupco @oviliz the resize part is sort of an unfinished feature. I totally forgot about it.  
youu can resize the images but in the css file still the width and height of the box are still 40px.  
I'll see what I can do in the next version.  
As for the color name after the label...I will try to do that but it's not very high priority.

**Comment by oviliz** [comment]
I'm sure that I've done that via CSS.
The "...50px!important" should help.

**Comment by oviliz** [comment]
PS. La multi ani! :)

**Comment by Jerry-Yocupco** [comment]
@tzyganu Thanks for the update, I will look forward to it

**Comment by tzyganu** [comment]
@Jerry-Yocupco Sorry for the late response. This bug should be fixed in version [2.2.0](https://github.com/tzyganu/Switcher/releases/tag/2.2.0)
