### ISSUE TITLE
Possible to select both attributes by default?

### ISSUE THREAD

**Issue by magejunkie** [tzyganu/Switcher#91]
Basically, what I need is a bit different from your extension.

I am already using Amasty's Color Swatch Pro and it selects the first color as default but doesn't select any size by default.

Is it possible I can select both Color and Size by default once the product page loads?

I dont want to load any specific attribute on page load, just load the product page with ANY attributes selected from Color and Size

**Comment by tzyganu** [comment]
Please ask Amasty for support.
