### ISSUE TITLE
Display color swatch on category-page

### ISSUE THREAD

**Issue by Nannica** [tzyganu/Switcher#93]
Thank you for a great extension!

I wonder if it-s possible to display color/image swatces for the products in the category catalog?

I've gotten so far as printing the attribute values, like this
<pre>
$color = array();
    $allProducts = $_product->getTypeInstance(true)->getUsedProducts(null, $_product);
    foreach ($allProducts as $subproduct) {

        $color[] = $subproduct->getAttributeText('attribute_key');

    }
        sort($color);
         echo implode(", ", $color);
</pre>

And that gives me the text-values that I made before using this plugin. But now I would like to show the actuall color/image. Is is possible?

**Comment by tzyganu** [comment]
@Nannica Sorry but this is not in the scope of the extension. you can use the default color swatches extension from magento 1.9.1 for this.
