### ISSUE TITLE
ConfigurableSwatches() - Undefined is not a function

### ISSUE THREAD

**Issue by Tilogorn** [tzyganu/Switcher#95]
I get an error for this line

`var swatchesConfig = new Product.ConfigurableSwatches(spConfig);`
"Uncaught TypeError: undefined is not a function"

I'm testing Switcher on a clean install of Magento 1.9.1, the built-in "Configurable Swatches"-Feature is turned off (as a test: turning it on didn't resolve the error). I manually uploaded every file in it's corresponding folder and doublechecked everything.

You can live-debug it in the test-store which is throwing the error (link to config test product)
http://dev.abutments4life.de/magento/index.php/test-kat/astratech-osseospeed-klebebasis-lts-baser-anguliert.html

Thanks for any hints :)

**Comment by tzyganu** [comment]
I wasn't able to reproduce this. Make sure the file that contains `ConfigurableSwatches` function is included in your DOM.

**Comment by ignaciomella** [comment]
I have the same error, but I see no lack of functionality. Just the error being displayed in Chrome's console as:

<code>Uncaught TypeError: Product.ConfigurableSwatches is not a function(anonymous function) @ bikini-cruzado-doblable-damasco:1033</code>

You can see it here http://www.lemps.cl/bikinis/bikini-cruzado-doblable-damasco

I would really appreciate if you briefly point me on how to include the file that contains <code>ConfigurableSwatches</code> function into my DOM.

:+1:

**Comment by kaiakonsap** [comment]
Hei!

I am using
Magento 1.9.1 and having the same error.
And I can't get the main image to change.
I actually would like to use only the feature that adds the default option and displays it as first in dropdown, it it better than some of the hacks I have tried for the same functionality. So maybe You can have extra small plugin made from the original for that, it would be lovely. Is it OK for me to try to get this part separated for using?

Thanks You for this great plugin!

**Comment by apothegm** [comment]
@Tilogorn @ignaciomella @kaiakonsap 

I was able to resolved this issue by disabling the core module Mage_ConfigurableSwatches.xml under /app/etc/modules. Change active to false.
