### ISSUE TITLE
Custom Images: Uploading images is not working in a server

### ISSUE THREAD

**Issue by johnsotelo** [tzyganu/Switcher#97]
Hi Guys! I had a problem with the uploading of images using easylife switcher. I can upload custom images on my local. But after I uploaded the extension to our server the uploading function of custom images of an attribute is inconsistently working. When I upload Black.png it works fine. When I tried to upload some colors like Blue White.png it did not capture and save the file. 

Hope you guys will help me to resolved this problem. I have already uploaded and check if I missed some items of extensions for how many times but still the problem occurred. Thank you so much!

**Comment by tzyganu** [comment]
I tried to reproduce this but I can't. Most probably there is an issue with your server.
