### ISSUE TITLE
How can I enable only color pre-defined?

### ISSUE THREAD

**Issue by epiblue** [tzyganu/Switcher#98]
I want to have the default color, but others not, can you advice what I would need to modify in the code?

Thanks,

**Comment by tzyganu** [comment]
@epiblue The default values are determined in the method `Easylife_Switcher_Block_Catalog_Product_View_Type_Configurable_Config::getDefaultValues`. See what happens int here and add the default values only for the attributes you need.  
I will close this since is not in the scope of the extension.

**Comment by epiblue** [comment]
OK, no problem, can you tell me in witch file? I'm not very used to module coding, thanks

**Comment by epiblue** [comment]
ok, found it :) Sorry for stupid question before :)

        if (!$this->getProduct()->hasPreconfiguredValues()) {
            if ($this->getDefaultValues()) {
                $config['defaultValues']    = $this->getDefaultValues();
            }
        }

It's this one right? Please how do I specify color here?

**Comment by epiblue** [comment]
should I use this: $config['defaultValues']    = $this->getAttribute('color'); ?

**Comment by tzyganu** [comment]
@epiblue This is the method you need to modify: https://github.com/tzyganu/Switcher/blob/master/app/code/community/Easylife/Switcher/Block/Catalog/Product/View/Type/Configurable/Config.php#L408

**Comment by epiblue** [comment]
Could you please, pretty please, make a quick modification example? 

getData(Easylife_Switcher_Helper_Data::DEFAULT_CONFIGURATION_ATTRIBUTE_CODE);

Should I simply overwrite DEFAULT_CONFIGURATION_ATTRIBUTE_CODE with mine attribute code or it's more complex than that?

Thank you very very much

**Comment by epiblue** [comment]
I'm trying like this, but it doesn't preselect it... $defaultId = $this->getProduct()->getAttributeData('color');

**Comment by tzyganu** [comment]
Try to see what that method returns without modifying anything and then try to make it return only what you need in the same format.

**Comment by epiblue** [comment]
How can I see what it returns?

I tryed this:
<?php Zend_Debug::dump(Mage::app()->getProduct()->getData(Easylife_Switcher_Helper_Data::DEFAULT_CONFIGURATION_ATTRIBUTE_CODE)); ?>

On the product page, but didn't get anything.

**Comment by epiblue** [comment]
Marius, Please, help me see what does it return, I'm trying to find something that would work, but everything I try is coming back as NULL.

As an example:
<?php Zend_Debug::dump($this->getProduct()->getData(Easylife_Switcher_Helper_Data::DEFAULT_CONFIGURATION_ATTRIBUTE_CODE), $label = null, $echo = true); ?>

Comes back NULL as well.

Please.

**Comment by epiblue** [comment]
Marius, please help me, I can't get to retrieve the values that are returned with this method...

I tryed everything... 

All the tips from here: 
http://stackoverflow.com/questions/10385048/php-var-dumpobject-or-print-robject-to-a-log-file

Please Marius, help me figure it out.

**Comment by epiblue** [comment]
I ended up hacking it... I don't know if you can all it a hack, but I used a trigger event with jQuery.

**Comment by tzyganu** [comment]
The method `getDefaultValues` returns an array like this `array('attr_id_1' => val1, 'attr_id_2'=>val2)`.  
Try to make it return only `array('color_attribute_id' => 'default value')`.
