### ISSUE TITLE
(Wishlist) Show available sizes in categorylisting

### ISSUE THREAD

**Issue by wchief** [tzyganu/Switcher#99]
Hi tzyganu,

Thank you for a solid mdoule .. we're very happy with it. Just wondered if its possible to extract the sizes below each product in a categorylisting? :)

**Comment by tzyganu** [comment]
@wchief It's not possible with the current implementation. And it will never be. This extension will not have any future upgrades since Magento has a Color Swatcher in the core starting with CE 1.9.

**Comment by wchief** [comment]
Hi there,

Thanks, ok - fair enough, but we're still greatful and very happy with your
app :-)

/Lars 

-----Oprindelig meddelelse-----
Fra: Marius Strajeru [mailto:notifications@github.com] 
Sendt: 21. marts 2015 23:29
Til: tzyganu/Switcher
Cc: wchief
Emne: Re: [Switcher] (Wishlist) Show available sizes in categorylisting
(#99)

@wchief <https://github.com/wchief>  It's not possible with the current
implementation. And it will never be. This extension will not have any
future upgrades since Magento has a Color Swatcher in the core starting with
CE 1.9.

-
Reply to this email directly or view it on GitHub
<https://github.com/tzyganu/Switcher/issues/99#issuecomment-84462781> .
<https://github.com/notifications/beacon/ALCzjAmPQKdDt88ZluuAg1TrJEdI_d4aks5
n3egkgaJpZM4DyVfg.gif>
